//
// Created by eric on 23-9-21.
//

#ifndef GIGACELL_GIGACELL_PLACEMENT_OPS_MOS_DIFFUSION_SHARING_H_
#define GIGACELL_GIGACELL_PLACEMENT_OPS_MOS_DIFFUSION_SHARING_H_

class MosDiffusionSharing {

};

#endif //GIGACELL_GIGACELL_PLACEMENT_OPS_MOS_DIFFUSION_SHARING_H_
